import 'dart:convert';
import 'dart:io';

import 'package:Kelivo/core/services/model_catalog/model_catalog_trim.dart';

const catalogProviderIds = <String>[
  'openai',
  'anthropic',
  'google',
  'google-vertex',
  'deepseek',
  'moonshotai',
  'alibaba',
  'zhipuai',
  'xai',
  'volcengine',
  'minimax',
  'stepfun',
  'mistral',
  'openrouter',
];

/// Extra ids from existing tests and request-layer families.
const extraCorpusIds = <String>[
  'qwen3.7-plus',
  'qwen3.7-flash',
  'qwen3.7-max-2026-06-08',
  'qwen3.7-max',
  'qwen3.7-max-2026-05-20',
  'qwen3.7-max-preview',
  'qwen3.7-max-2026-05-17',
  'qwen3.8-max',
  'qwen3.8-flash',
  'qwen3.8-27b',
  'qwen3.8-2.4t-a95b',
  'qwen3-max',
  'qwen3-thinking',
  'qwq-32b',
  'deepseek-flash',
  'deepseek/deepseek-flash',
  'deepseek-v4-flash',
  'deepseek-v4-flash-vision-exp',
  'deepseek-v4-pro',
  'deepseek-r1',
  'deepseek-reasoner',
  'deepseek-chat',
  'deepseek-v3.2',
  'doubao-seed-2.0-pro',
  'doubao-seed-2.0-code',
  'doubao-seed-2-1-pro-260628',
  'doubao-seed-2.1-turbo',
  'doubao-seed-evolving',
  'gpt-6-astra',
  'openai/gpt-6-astra',
  'muse-spark-1.3',
  'muse-spark-1.3-contributor',
  'muse-spark-1.1',
  'muse-spark-1',
  'meta/muse-spark-1.2',
  'glm-5.3-flash',
  'glm-5.3',
  'z-ai/glm-5.3',
  'glm-5.2',
  'z-ai/glm-5.2',
  'glm-4.5',
  'glm-4.6',
  'glm-4.7',
  'k3',
  'k3-256k',
  'k30',
  'my-k3',
  'kimi-for-coding',
  'kimi-for-coding-highspeed',
  'kimi-for-coding-other',
  'moonshotai/kimi-for-coding:fast',
  'kimi-k2.8',
  'moonshotai/kimi-k2.8-preview',
  'kimi-k2.7-code',
  'kimi-k2.7',
  'kimi-k2.6',
  'kimi-k2.5',
  'kimi-k2-thinking',
  'kimi-k3',
  'moonshotai/kimi-k3',
  'gpt-5.6-sol',
  'gpt-5.6-terra',
  'gpt-5.6-luna',
  'openai/gpt-5.6-sol',
  'gpt-5.5',
  'gpt-5.5-pro',
  'gpt-5.5-codex',
  'gpt-5.4',
  'gpt-5.4-pro',
  'gpt-5.3-codex',
  'gpt-5.3-pro',
  'gpt-5.3-chat-latest',
  'gpt-5.2',
  'gpt-5.2-pro',
  'gpt-5.2-codex',
  'gpt-5.2-chat-latest',
  'gpt-5.1',
  'gpt-5.1-codex',
  'gpt-5.1-codex-max',
  'gpt-5.1-pro',
  'gpt-5.1-chat-latest',
  'gpt-5',
  'gpt-5-pro',
  'gpt-5-codex',
  'gpt-5-chat-latest',
  'gpt-4o',
  'gpt-4.1',
  'gpt-oss-120b',
  'o1',
  'o1-preview',
  'o3',
  'openai/o3',
  'o3-mini',
  'o4-mini',
  'grok-4.5',
  'x-ai/grok-4.5',
  'grok-4.6',
  'x-ai/grok-4.6',
  'x-ai/grok-4',
  'gemini-3.5-flash',
  'gemini-3.5-flash-lite',
  'gemini-3.6-flash',
  'gemini-3.7-flash',
  'gemini-3.8-flash',
  'gemini-3.1-pro-preview',
  'gemini-3-pro',
  'gemini-3-pro-image-preview',
  'gemini-3.1-flash-image',
  'gemini-3.1-flash-lite-image',
  'gemini-3.1-flash-image-preview',
  'gemini-3.1-flash-tts-preview',
  'gemini-2.5-flash',
  'gemini-2.5-pro',
  'gemini-flash-latest',
  'gemini-pro-latest',
  'google/gemma-4-27b',
  'gemma-4',
  'claude-fable-5-1',
  'claude-fable-5',
  'claude-mythos-5',
  'claude-opus-4-8',
  'claude-opus-4.8',
  'claude-opus-4-7',
  'claude-opus-4-6',
  'claude-opus-5',
  'claude-sonnet-5',
  'claude-sonnet-4-6',
  'claude-sonnet-4.6',
  'claude-haiku-4-5',
  'claude-3-5-sonnet',
  'claude-3-haiku@20240307',
  'claude-3-5-sonnet@20240620',
  'claude-3-5-sonnet-v2@20241022',
  'claude-opus-4-5@20251101',
  'claude-sonnet-4-5@20250929',
  'claude-haiku-4-5@20251001',
  'claude-sonnet-4@20250514',
  'claude-opus-4-1@20250805',
  'claude-opus-4@20250514',
  'gpt-image-1',
  'gpt-image-2',
  'chatgpt-image-latest',
  'agnes-image-1',
  'sensenova-u1-fast',
  'dall-e-2',
  'dall-e-3',
  'text-embedding-3-large',
  'text-embedding-3-small',
  'qwen3-embedding-8b',
  'mistral-embed',
  'jina-embeddings-v3',
  'laguna-70b',
  'acme/laguna-8b',
  'mimo-v2',
  'mimo-v2.5-pro',
  'xiaomi/mimo-v2.5',
  'sensenova-6.7-flash-lite',
  'minimax-m2',
  'minimax-m2.1',
  'minimax-m3',
  'step-3',
  'intern-s1',
];

List<String> modelSpecCorpusIds({
  String catalogPath = 'assets/model_catalog/models_dev.json',
}) {
  final ids = <String>{...extraCorpusIds};
  final file = File(catalogPath);
  final json = jsonDecode(file.readAsStringSync()) as Map<String, dynamic>;
  final catalog = parseTrimmedCatalog(json);
  for (final providerId in catalogProviderIds) {
    final provider = catalog.providers[providerId];
    if (provider == null) continue;
    ids.addAll(provider.models.keys);
  }
  final list = ids.toList()..sort();
  return list;
}
